apiVersion: v1
kind: Secret
metadata:
  name: data-secret
type: Opaque
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: eWVz
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: data-secret-script
type: Opaque
data:
  MYSQL_USER_PASSWORD: cm9vdA==
  MYSQL_USER: cm9vdA==
  MYSQL_DB_HOST: ZGF0YQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: back-secret
type: Opaque
data:
  SQLALCHEMY_DATABASE_URI: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdEBkYXRhOjMzMDYvbXlkYXRhYmFzZQ==