apiVersion: v1
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: eWVz
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: "2021-09-22T17:09:25Z"
  name: data-deployment
  namespace: default
  resourceVersion: "319302"
  selfLink: /api/v1/namespaces/default/secrets/data-deployment
  uid: 67be0442-29e7-42f3-8532-d39d82590cf0
type: Opaque
~              